server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/citylearn?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.citylearn.entity
logging:
  level:
    com.citylearn.dao: debug
    org.mybatis: debug
    org.apache.ibatis: debug
